[theme]
base="dark"
primaryColor="#60a5fa"                 # modern blue (tailwind-like)
backgroundColor="#1f2937"              # charcoal (almost black, not jet)
secondaryBackgroundColor="#111827"     # deep slate gray (for cards)
textColor="#f3f4f6"                    # soft white (not pure white)
font="sans serif"
[theme.sidebar]
backgroundColor="#1e293b"
textColor="#cbd5e1"